{"products": [
        {
            "id": 48,
            "link": "http:\/\/transformer.sunnytoo.com\/twelfth\/en\/electronics\/48-synthetic-leather-mens-adjustable-casual-buckle-belt.html",
            "quantity": 2,
            "image": "http:\/\/transformer.sunnytoo.com\/twelfth\/109-thumb_default\/synthetic-leather-mens-adjustable-casual-buckle-belt.jpg",
            "image_width": "56",
            "image_height": "64",
            "image_cart": "http:\/\/transformer.sunnytoo.com\/twelfth\/109-small_default\/synthetic-leather-mens-adjustable-casual-buckle-belt.jpg",
            "priceByLine": "$38.00",
            "name": "Synthetic Leather Mens Adjustable Casual buckle Belt",
            "full_name": "Synthetic Leather Mens Adjustable Casual buckle Belt",
            "price": "$38.00",
            "price_float": 38,
            "idCombination": 0,
            "idAddressDelivery": 0,
            "is_gift": false,
            "hasAttributes": false,
            "hasCustomizedDatas": false,
            "customizedDatas": []
        },
        {
            "id": 15,
            "link": "http:\/\/transformer.sunnytoo.com\/twelfth\/en\/home\/15-new-fashion-vintage-double-breasted-trench-long-sleeve-coat-jacket-outwear-1234567890123.html",
            "quantity": 1,
            "image": "http:\/\/transformer.sunnytoo.com\/twelfth\/27-thumb_default\/new-fashion-vintage-double-breasted-trench-long-sleeve-coat-jacket-outwear.jpg",
            "image_width": "56", "image_height": "64",
            "image_cart": "http:\/\/transformer.sunnytoo.com\/twelfth\/27-small_default\/new-fashion-vintage-double-breasted-trench-long-sleeve-coat-jacket-outwear.jpg",
            "priceByLine": "$39.89",
            "name": "New Fashion Vintage Double Breasted Trench Long Sleeve Coat Jacket Outwear",
            "full_name": "New Fashion Vintage Double Breasted Trench Long Sleeve Coat Jacket Outwear",
            "price": "$39.89",
            "price_float": 39.89,
            "idCombination": 0,
            "idAddressDelivery": 0,
            "is_gift": false,
            "hasAttributes": false,
            "hasCustomizedDatas": false,
            "customizedDatas": []
        },
        {
            "id": 9,
            "link": "http:\/\/transformer.sunnytoo.com\/twelfth\/en\/fashion\/9-half-sleeves-taffeta-bridal-jacket-1234567890123.html#\/size-s\/color-black",
            "quantity": 1,
            "image": "http:\/\/transformer.sunnytoo.com\/twelfth\/15-thumb_default\/half-sleeves-taffeta-bridal-jacket.jpg",
            "image_width": "56",
            "image_height": "64",
            "image_cart": "http:\/\/transformer.sunnytoo.com\/twelfth\/15-small_default\/half-sleeves-taffeta-bridal-jacket.jpg",
            "priceByLine": "$45.62",
            "name": "Half Sleeves Taffeta Bridal Jacket",
            "full_name": "Half Sleeves Taffeta Bridal Jacket",
            "price": "$45.62",
            "price_float": 45.62,
            "idCombination": 13,
            "idAddressDelivery": 0,
            "is_gift": false,
            "hasAttributes": true,
            "attributes": "Black, S",
            "hasCustomizedDatas": false,
            "customizedDatas": []
        },
        {
            "id": 10,
            "link": "http:\/\/transformer.sunnytoo.com\/twelfth\/en\/fashion\/10-beautiful-lace-half-sleeve-casual-party-jacket-1234567890123.html#\/size-s\/color-black",
            "quantity": 1,
            "image": "http:\/\/transformer.sunnytoo.com\/twelfth\/17-thumb_default\/beautiful-lace-half-sleeve-casual-party-jacket.jpg",
            "image_width": "56",
            "image_height": "64",
            "image_cart": "http:\/\/transformer.sunnytoo.com\/twelfth\/17-small_default\/beautiful-lace-half-sleeve-casual-party-jacket.jpg",
            "priceByLine": "$14.08",
            "name": "Beautiful Lace Half-Sleeve Casual\/Party Jacket",
            "full_name": "Beautiful Lace Half-Sleeve Casual\/Party Jacket",
            "price": "$14.08",
            "price_float": 14.08,
            "idCombination": 17,
            "idAddressDelivery": 0,
            "is_gift": false,
            "hasAttributes": true,
            "attributes": "Black, S",
            "hasCustomizedDatas": false,
            "customizedDatas": []
        }
    ],
    "discounts": [],
    "shippingCost": "$27.00",
    "shippingCostFloat": 27,
    "wrappingCost": "$0.00",
    "nbTotalProducts": 5,
    "total": "$164.59",
    "productTotal": "$137.59",
    "freeShipping": "$0.00",
    "freeShippingFloat": 0,
    "free_ship": false,
    "isVirtualCart": false,
    "hasError": false
}
